# Generated by Django 5.2.5 on 2025-08-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
